[game]
audience = "everyone"
ai = "unused"
orientation = "natural"
inputs = [
  "keyboard-mouse",
  "touch"
]
visibility = "unlisted"

[workflow]
build = "npm run build"
deploy_dir = ".arcadible-public"
